version: '3.1'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bondbaas-db
      - POSTGRES_USER=bondbaas
      - POSTGRES_PASSWORD=bondbaas
  app:
    build: .
    volumes:
      - .:/go/src/bondbaas
    command: fresh
    command: ["./wait-for-it.sh", "db:5432", "--", "fresh"]
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=bondbaas-db
      - DB_USER=bondbaas
      - DB_PASSWORD=bondbaas
      - APP_PORT=3000
    depends_on:
      - db
